### ISSUE TITLE
Feature - Supplemental resources on imported dojos

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#296]
Currently if a dojo directly imports a topic module wholesale it also imports the resources from the imported module, which makes sense.

However, if the course dojo.yml imported module defines additional resources, such as links to live lectures or any course specific content this will overwrite the topic's resources.  It would be nice for imported modules to be able to list "supplemental resources" without needing to ether import a topic dojo piece by piece OR re-listing the topic dojo's resources.

Example dojo.yml content
```
- import:
    dojo: software-exploitation
    module: speculative-execution
  resources:
    - name: "Class - Robert - 2024.01.16"
      type: lecture
      video: p35mAF_4y-4
      playlist: PL-ymxv0nOtqr7zM7ZBREoWa-eeSaKFJQd
      slides: 1b8XO7qtUbHDHyzWcNc1bdO6jMmbtzCqjC2IInZZuenI
    - name: Further Reading
      type: markdown
      content: |
        - [The original spectre research paper](https://spectreattack.com/spectre.pdf)
        - [The original meltdown research paper](https://meltdownattack.com/meltdown.pdf)
```
