### ISSUE TITLE
consider bringing back support for yaml-only dojos

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#311]
Having dojos in git repos is the only sane option for people making dojos, but it's a big PITA for testing. It would be nice if we can just POST some yaml to the `create` endpoint in our test scripts and have the dojos created. I'm thinking something like:

```
id: test-dojo
modules:
- id: test-module
  challenges:
  - id: test-challenge
    files:
    - run: "#!/opt/pwn.college/bash\ncat /flag"
```

I think this would really amp up our testing capabilities.
