### ISSUE TITLE
Adding challenges

### ISSUE THREAD

**Issue by Tomal-kuet** [pwncollege/dojo#56]
We have set the instance and the website is running successfully. But we are facing some issues regarding how to add challenges. We have created the modules.yml file as below:

```
- name: Buffer-overflow-exmaple
  permalink: Buffer-overflow-1
  challenges:
    - category: Buffer-overflow/
      names:
        - overflowlocal2_64
```
And the directory instruction and the binary are put as shown by the screenshot. Everything is getting copied correctly to the **pwn.college** docker container, but the challenges are not updated on the website or the database. Can you please guide us on what we are doing wrong here?

![2022-05-19_10-51](https://user-images.githubusercontent.com/16141696/169326362-6b6061d5-fc9d-4cfd-9e97-58c11d5871b6.png)
